// Code generated by Kitex v1.16.4. DO NOT EDIT.

package lepuser

import (
	lep_user "bupt/lep_user/kitex_gen/lep_user"
	byted "code.byted.org/kite/kitex/byted"
	client "code.byted.org/kite/kitex/client"
	callopt "code.byted.org/kite/kitex/client/callopt"
	"context"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PermissionList(ctx context.Context, req *lep_user.PermissionListRequest, callOptions ...callopt.Option) (r *lep_user.PermissionListResp, err error)
	UpsertPermission(ctx context.Context, req *lep_user.UpsertMaterialRequest, callOptions ...callopt.Option) (r *lep_user.UpsertPermissionResp, err error)
	RoleList(ctx context.Context, req *lep_user.RoleListRequest, callOptions ...callopt.Option) (r *lep_user.RoleListResp, err error)
	UpsertRole(ctx context.Context, req *lep_user.UpsertRoleRequest, callOptions ...callopt.Option) (r *lep_user.UpsertRoleResp, err error)
	UserList(ctx context.Context, req *lep_user.UserListRequest, callOptions ...callopt.Option) (r *lep_user.UserListResp, err error)
	UpsertUser(ctx context.Context, req *lep_user.UpsertUserRequest, callOptions ...callopt.Option) (r *lep_user.UpsertUserResp, err error)
	MaterialList(ctx context.Context, req *lep_user.MaterialListRequest, callOptions ...callopt.Option) (r *lep_user.MaterialListResp, err error)
	UpsertMaterial(ctx context.Context, req *lep_user.UpsertMaterialRequest, callOptions ...callopt.Option) (r *lep_user.UpsertMaterialResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	config := byted.NewClientConfig()
	config.DestService = destService
	options = append(options, byted.ClientSuiteWithConfig(serviceInfoForClient(), config))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLepUserClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLepUserClient struct {
	*kClient
}

func (p *kLepUserClient) PermissionList(ctx context.Context, req *lep_user.PermissionListRequest, callOptions ...callopt.Option) (r *lep_user.PermissionListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PermissionList(ctx, req)
}

func (p *kLepUserClient) UpsertPermission(ctx context.Context, req *lep_user.UpsertMaterialRequest, callOptions ...callopt.Option) (r *lep_user.UpsertPermissionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpsertPermission(ctx, req)
}

func (p *kLepUserClient) RoleList(ctx context.Context, req *lep_user.RoleListRequest, callOptions ...callopt.Option) (r *lep_user.RoleListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RoleList(ctx, req)
}

func (p *kLepUserClient) UpsertRole(ctx context.Context, req *lep_user.UpsertRoleRequest, callOptions ...callopt.Option) (r *lep_user.UpsertRoleResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpsertRole(ctx, req)
}

func (p *kLepUserClient) UserList(ctx context.Context, req *lep_user.UserListRequest, callOptions ...callopt.Option) (r *lep_user.UserListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserList(ctx, req)
}

func (p *kLepUserClient) UpsertUser(ctx context.Context, req *lep_user.UpsertUserRequest, callOptions ...callopt.Option) (r *lep_user.UpsertUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpsertUser(ctx, req)
}

func (p *kLepUserClient) MaterialList(ctx context.Context, req *lep_user.MaterialListRequest, callOptions ...callopt.Option) (r *lep_user.MaterialListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MaterialList(ctx, req)
}

func (p *kLepUserClient) UpsertMaterial(ctx context.Context, req *lep_user.UpsertMaterialRequest, callOptions ...callopt.Option) (r *lep_user.UpsertMaterialResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpsertMaterial(ctx, req)
}

// NewClientWithBytedConfig creates a client for the service defined in IDL.
func NewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) (Client, error) {
	if config == nil {
		config = byted.NewClientConfig()
	}
	config.DestService = destService

	var options []client.Option
	options = append(options, client.WithDestService(destService))

	clientServiceInfo := serviceInfoForClient()
	options = append(options, byted.ClientSuiteWithConfig(clientServiceInfo, config))
	options = append(options, opts...)
	kc, err := client.NewClient(clientServiceInfo, options...)
	if err != nil {
		return nil, err
	}
	return &kLepUserClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClientWithBytedConfig creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClientWithBytedConfig(destService string, config *byted.ClientConfig, opts ...client.Option) Client {
	kc, err := NewClientWithBytedConfig(destService, config, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}
